from requests import put, get
from random import randint

servers = [
    'http://localhost:5000',
    'http://localhost:5001',
    'http://localhost:5002',
]


sentences = ['Aequam igitur pronuntiabitsententiam ratio adhibita primum divinarum humanarumque rerumscientia, quae potest appellaririte sapientia, deinde adiunctisvirtutibus, quas ratio rerum omnium dominas, tu voluptatumsatellites et ministras essevoluisti.',
             'Pertinere autem ad rem arbitrantur intellegi natura fieri ut liberi a parentibus amentur.',
             'Huc et illuc, Torquate, vosversetis licet, nihil in hac praeclara epistula scriptum ab Epicurocongruens et conveniensdecretis eius reperietis.',
             'Haec ego non possum dicere nonesse hominis quamvis et belli et humani, sapientis vero nullo modo, physici praesertim,quem se ille esse vult, putare ullum essecuiusquam diem natalem.',
             'Atque perspicuum etiam illud est, in istis rebus mediis aliquid agere sapientem.',
             'Quare aliud aliquod, Torquate, hominis summum bonum reperiendum est, voluptatem bestiisconcedamus, quibus vos de summobono testibus uti soletis.',
             'Quid?',
             'Sed cum, quod honestum sit, id solum bonum esse dicamus, consentaneum tamen est fungi officio, cum id officium nec inbonis ponamus nec in malis.',
             'Sed dumefficere vultis beatum sapientem, cum maximas animo voluptatespercipiat omnibusque partibus maiores quam corpore,quid occurratnon videtis.',
             'Tribus igitur modis video esse a nostris de amicitia disputatum.',
             'Iis igitur est difficilius satis facere, qui se Latina scripta dicunt contemnere.',
             'Verum esto: verbum ipsumvoluptatis non habet dignitatem, nec nos fortasse intellegimus.',
             'Ut enim obscuratur et offunditur luce solis lumen lucernae, et ut interit magnitudine maris Aegaei stilla mellis,et ut in divitiis Croesi teruncii accessio et gradus unus in ea via, quae est hinc in Indiam, sic, cum sit is bonorumfinis, quem Stoici dicunt, omnis ista rerum corporearum aestimatio splendore virtutis et magnitudine obscuretur etobruatur atque intereat necesse est.',
             'Videamus nunc, quam sint praeclare illa his, quae iam posui, consequentia.',
             'Traditur, inquit, ab Epicuro rationeglegendi doloris.',
             'Dic in quovis conventu te omniafacere, ne doleas.',
             'Aequam igitur pronuntiabitsententiam ratio adhibita primum divinarum humanarumque rerumscientia, quae potest appellaririte sapientia, deinde adiunctisvirtutibus, quas ratio rerum omnium dominas, tu voluptatumsatellites et ministras essevoluisti.',
             'Nec vero ignoro varias philosophorum fuisse sententias, eorum dico, qui summum bonum, quod ultimum appello, in animoponerent.',
             'Huc et illuc, Torquate, vosversetis licet, nihil in hac praeclara epistula scriptum ab Epicurocongruens et conveniensdecretis eius reperietis.',
             'Quodsi corporis gravioribus morbis vitae iucunditas impeditur, quanto magis animi morbis impediri necesse est!',
             'Quod autem magnum dolorem brevem, longinquum levem esse dicitis, id non intellego quale sit.',
             'Sunt autem quidam Epicurei timidiores paulo contra vestra convicia, sed tamen satis acuti, qui verentur ne, si amicitiampropter nostram voluptatem expetendam putemus, tota amicitia quasi claudicare videatur.',
             'Quapropter si ea, quae dixi, sole ipso illustriora et clariora sunt, si omnia dixi hausta e fonte naturae, si totaoratio nostra omnem sibi fidem sensibus confirmat, id est incorruptis atque integris testibus, si infantes pueri, mutaeetiam bestiae paene loquuntur magistra ac duce natura nihil esse prosperum nisi voluptatem, nihil asperum nisi dolorem,de quibus neque depravate iudicant neque corrupte, nonne ei maximam gratiam habere debemus, qui hac exaudita quasi vocenaturae sic eam firme graviterque comprehenderit, ut omnes bene sanos in viam placatae, tranquillae, quietae, beataevitae deduceret?',
             'Hanc ego cum teneam sententiam, quid est cur verear, ne ad eam non possim accommodare Torquatos nostros?',
             'Traditur, inquit, ab Epicuro rationeglegendi doloris.',
             'Ut vero conservetur omnis homini erga hominem societas, coniunctio, caritas, et emolumenta et detrimenta, quae etappellant, communia esse voluerunt; quorum altera prosunt, nocent altera.',
             'Multi enim et magni philosophihaec ultima bonorum iuncta fecerunt, ut Aristoteles virtutis usumcum vitae perfectaeprosperitate coniunxit, Callipho adiunxit adhonestatem voluptatem, Diodorus ad eandem honestatem addiditvacuitatemdoloris.',
             'Iustitia restat, ut de omni virtute sit dictum.',
             'Circumscriptis igitur iis sententiis, quas posui, et iis, si quae similes earum sunt, relinquitur ut summum bonum sitvivere scientiam adhibentem earum rerum, quae natura eveniant, seligentem quae secundum naturam et quae contra naturamsint reicientem, id est convenienter congruenterque naturae vivere.',
             'Elicerem ex te cogeremque, utresponderes, nisi vererer ne Herculem ipsum ea, quae pro salutegentium summo laboregessisset, voluptatis causa gessisse diceres.',
             'Ita tres sunt fines experteshonestatis, unus Aristippi vel Epicuri, alter Hieronymi, Carneaditertius, tres, in quibushonestas cum aliqua accessione, Polemonis, Calliphontis, Diodori, una simplex, cuius Zeno auctor, posita indecore tota,id est in honestate; nam Pyrrho, Aristo, Erillus iamdiu abiecti.',
             'Haec mirabilia videri intellego, sed cum certe superiora firma ac vera sint, his autem ea consentanea et consequentia,ne de horum quidem est veritate dubitandum.',
             'Verum esto: verbum ipsumvoluptatis non habet dignitatem, nec nos fortasse intellegimus.',
             'Audio equidem philosophi vocem, Epicure, sed quid tibi dicendum sit oblitus es.',
             'Stuprata per vim Lucretia a regisfilio testata civis se ipsa interemit.',
             'Amicitiam autem adhibendam esse censent, quia sit ex eo genere, quae prosunt.',
             'Habes undique expletam etperfectam, Torquate, formam honestatis, quae tota quattuor hisvirtutibus, quae a te quoquecommemoratae sunt, continetur.',
             'Dic in quovis conventu te omniafacere, ne doleas.',
             'Audio equidem philosophi vocem, Epicure, sed quid tibi dicendum sit oblitus es.',
             'Lege laudationes, Torquate, noneorum, qui sunt ab Homero laudati, non Cyri, non Agesilai, nonAristidi aut Themistocli,non Philippi aut Alexandri, legenostrorum hominum, lege vestrae familiae; neminem videbis italaudatum, ut artifexcallidus comparandarum voluptatum diceretur.',
             'Sed haec nihil sane ad rem; illavideamus, quae a te de amicitia dicta sunt.',
             'Sed possunt haec quadam ratione dici non modo non repugnantibus, verum etiam approbantibus nobis.',
             'Hunc vos beatum; ratio quidemvestra sic cogit.',
             'Semovenda est igitur voluptas, nonsolum ut recta sequamini, sed etiam ut loqui deceat frugaliter.',
             'Bestiarum vero nullum iudiciumputo.',
             'Contineo me ab exemplis.',
             'Iis igitur est difficilius satis facere, qui se Latina scripta dicunt contemnere.',
             'Extremum autem esse bonorum voluptatem ex hoc facillime perspici potest: Constituamus aliquem magnis, multis, perpetuisfruentem et animo et corpore voluptatibus nullo dolore nec impediente nec inpendente, quem tandem hoc statupraestabiliorem aut magis expetendum possimus dicere?',
             'Quapropter si ea, quae dixi, sole ipso illustriora et clariora sunt, si omnia dixi hausta e fonte naturae, si totaoratio nostra omnem sibi fidem sensibus confirmat, id est incorruptis atque integris testibus, si infantes pueri, mutaeetiam bestiae paene loquuntur magistra ac duce natura nihil esse prosperum nisi voluptatem, nihil asperum nisi dolorem,de quibus neque depravate iudicant neque corrupte, nonne ei maximam gratiam habere debemus, qui hac exaudita quasi vocenaturae sic eam firme graviterque comprehenderit, ut omnes bene sanos in viam placatae, tranquillae, quietae, beataevitae deduceret?',
             'Nec vero ignoro varias philosophorum fuisse sententias, eorum dico, qui summum bonum, quod ultimum appello, in animoponerent.',
             'Sed ut epistulam laudandamarbitror eam, quam modo totidem fere verbis interpretatus sum, quamquam ea cum summa eiusphilosophia nullo modo congruebat, siceiusdem testamentum non solum philosophi gravitate, sedetiam ab ipsiussententia iudico discrepare.',
             'Quae cum dixissem, magis ut illum provocarem quam ut ipse loquerer, tum Triarius leniter arridens: Tu quidem, inquit,totum Epicurum paene e philosophorum choro sustulisti.',
             'Sed tamen nonne reprehenderes, Epicure, luxuriosos ob eam ipsam causam, quod ita viverent, utpersequerentur cuiusquemodi voluptates, cum esset praesertim, utais tu, summa voluptas nihil dolere?',
             'Sed ex hoc primum error tollendus est, ne quis sequi existimet, ut duo sint ultima bonorum.',
             'Sed ut omittam pericula, labores, dolorem etiam, quem optimus quisque pro patria et pro suis suscipit, ut non modonullam captet, sed etiam praetereat omnes voluptates, dolores denique quosvis suscipere malit quam deserere ullamofficii partem, ad ea, quae hoc non minus declarant, sed videntur leviora, veniamus.',
             'Quoniam igitur omnis summaphilosophiae ad beate vivendum refertur, idque unum expetenteshomines se ad hoc studiumcontulerunt, beate autem vivere alii inalio, vos in voluptate ponitis, item contra miseriam omnem indolore, id primumvideamus, beate vivere vestrum quale sit.',
             'Eadem fortitudinis ratio reperietur.',
             'Invitat igitur vera ratio bene sanos ad iustitiam, aequitatem, fidem, neque homini infanti aut inpotenti iniuste factaconducunt, qui nec facile efficere possit, quod conetur, nec optinere, si effecerit, et opes vel fortunae vel ingeniiliberalitati magis conveniunt, qua qui utuntur, benivolentiam sibi conciliant et, quod aptissimum est ad quietevivendum, caritatem, praesertim cum omnino nulla sit causa peccandi.',
             'Ut vero conservetur omnis homini erga hominem societas, coniunctio, caritas, et emolumenta et detrimenta, quae etappellant, communia esse voluerunt; quorum altera prosunt, nocent altera.',
             'Ita tres sunt fines experteshonestatis, unus Aristippi vel Epicuri, alter Hieronymi, Carneaditertius, tres, in quibushonestas cum aliqua accessione, Polemonis, Calliphontis, Diodori, una simplex, cuius Zeno auctor, posita indecore tota,id est in honestate; nam Pyrrho, Aristo, Erillus iamdiu abiecti.',
             'Id qui in una virtute ponunt et splendore nominis capti quid natura postulet non intellegunt, errore maximo, si Epicurumaudire voluerint, liberabuntur: istae enim vestrae eximiae pulchraeque virtutes nisi voluptatem efficerent, quis eas autlaudabilis aut expetendas arbitraretur?',
             'Cupiditates non Epicuri divisionefiniebat, sed sua satietate.',
             'Haec ego non possum dicere nonesse hominis quamvis et belli et humani, sapientis vero nullo modo, physici praesertim,quem se ille esse vult, putare ullum essecuiusquam diem natalem.',
             'Synephebos ego, inquit, potius Caecilii aut Andriam Terentii quam utramque Menandri legam?',
             'Ut enim, inquit, nemo dicit in regia regem ipsum quasi productum esse ad dignitatem (id est enim prohgmanon), sed eos,qui in aliquo honore sunt, quorum ordo proxime accedit, ut secundus sit, ad regium principatum, sic in vita non ea, quaeprimo loco sunt, sed ea, quae secundum locum optinent, prohgmana, id est producta, nominentur; quae vel itaappellemus - id erit verbum e verbo - vel promota et remota vel, ut dudum diximus, praeposita vel praecipua, et illareiecta.',
             'Illud autem ipsum qui optineripotest, quod dicitis, omnis animi et voluptates et dolores adcorporis voluptates acdolores pertinere?',
             'Iam in altera philosophiae parte.',
             'Ut igitur illis, qui, recta ethonesta quae sunt, ea statuunt per se expetenda, adeunda sunt saepepericula decorishonestatisque causa, sic vestris, qui omniavoluptate metiuntur, pericula adeunda sunt, ut adipiscantur magnasvoluptates.',
             'Amicitiae vero locus ubi essepotest aut quis amicus esse cuiquam, quem non ipsum amet propteripsum?',
             'Deinceps explicatur differentia rerum, quam si non ullam esse diceremus, confunderetur omnis vita, ut ab Aristone, nequeullum sapientiae munus aut opus inveniretur, cum inter res eas, quae ad vitam degendam pertinerent, nihil omninointeresset, neque ullum dilectum adhiberi oporteret.',
             'Dic in quovis conventu te omniafacere, ne doleas.',
             'Istud quidem, inquam, optime dicis, sed quaero nonne tibi faciendum idem sit nihil dicenti bonum, quod non rectumhonestumque sit, reliquarum rerum discrimen omne tollenti.',
             'Cupiditates non Epicuri divisionefiniebat, sed sua satietate.',
             'Haec igitur Epicuri non probo, inquam.',
             'Quae dici eadem de ceterisvirtutibus possunt, quarum omnium fundamenta vos in voluptatetamquam in aqua ponitis.',
             'Ita tres sunt fines experteshonestatis, unus Aristippi vel Epicuri, alter Hieronymi, Carneaditertius, tres, in quibushonestas cum aliqua accessione, Polemonis, Calliphontis, Diodori, una simplex, cuius Zeno auctor, posita indecore tota,id est in honestate; nam Pyrrho, Aristo, Erillus iamdiu abiecti.',
             'Posuisti etiam dicere alios foedusquoddam inter se facere sapientis, ut, quem ad modum sint in seipsos animati, eodemmodo sint erga amicos; id et fieri posse etsaepe esse factum et ad voluptates percipiendas maxime pertinere.',
             'Huic certae stabilique sententiae quae sint coniuncta explicabo brevi.',
             'Sed cum ab his omnia proficiscantur officia, non sine causa dicitur ad ea referri omnes nostras cogitationes, in his etexcessum e vita et in vita mansionem.',
             'Nec plura paucioribus nec longinquiora brevioribus anteponent.',
             'Quam ob rem tandem, inquit, non satisfacit?',
             'An potest, inquit ille, quicquamesse suavius quam nihil dolere?',
             'Sed ut omittam pericula, labores, dolorem etiam, quem optimus quisque pro patria et pro suis suscipit, ut non modonullam captet, sed etiam praetereat omnes voluptates, dolores denique quosvis suscipere malit quam deserere ullamofficii partem, ad ea, quae hoc non minus declarant, sed videntur leviora, veniamus.',
             'Voluptatem quidem, Brute, si ipsa pro se loquatur nec tam pertinaces habeat patronos, concessuram arbitror convictamsuperiore libro dignitati.',
             'Quis, quaeso, inquit, est, qui quidsit voluptas nesciat, aut qui, quo magis id intellegat, definitionem aliquamdesideret?',
             'Posuisti etiam dicere alios foedusquoddam inter se facere sapientis, ut, quem ad modum sint in seipsos animati, eodemmodo sint erga amicos; id et fieri posse etsaepe esse factum et ad voluptates percipiendas maxime pertinere.',
             'Idne consensisse de Calatinoplurimas gentis arbitramur, primarium populi fuisse, quodpraestantissimus fuisset inconficiendis voluptatibus?',
             'Haec mirabilia videri intellego, sed cum certe superiora firma ac vera sint, his autem ea consentanea et consequentia,ne de horum quidem est veritate dubitandum.',
             'Ius autem, quod ita dici appellarique possit, id esse natura, alienumque esse a sapiente non modo iniuriam cui facere,verum etiam nocere.',
             'Sed dum dialecticam, Torquate, contemnit Epicurus, quae una continet omnem et perspiciendi quid inquaque re sitscientiam et iudicandi quale quidque sit et rationeac via disputandi, ruit in dicendo, ut mihi quidem videtur, nec ea,quae docere vult, ulla arte distinguit, ut haec ipsa, quae modoloquebamur.',
             'Bonum autem, quod in hoc sermone totiens usurpatum est, id etiam definitione explicatur.',
             'Videmus in quodam volucriumgenere non nulla indicia pietatis, cognitionem, memoriam, in multisetiam desideria videmus.',
             'Haec mirabilia videri intellego, sed cum certe superiora firma ac vera sint, his autem ea consentanea et consequentia,ne de horum quidem est veritate dubitandum.',
             'Haec mirabilia videri intellego, sed cum certe superiora firma ac vera sint, his autem ea consentanea et consequentia,ne de horum quidem est veritate dubitandum.',
             'Haec dicuntur inconstantissime.',
             'Quid?',
             'Sed possunt haec quadam ratione dici non modo non repugnantibus, verum etiam approbantibus nobis.',
             'Nec vero ignoro varias philosophorum fuisse sententias, eorum dico, qui summum bonum, quod ultimum appello, in animoponerent.',
             'Verum hoc loco sumo verbis his eandemcerte vim voluptatis Epicurum nosse quam ceteros.',
             'Ut vero conservetur omnis homini erga hominem societas, coniunctio, caritas, et emolumenta et detrimenta, quae etappellant, communia esse voluerunt; quorum altera prosunt, nocent altera.']


for i in range(100):
    r = put('{}/cache/key{}'.format(servers[randint(0, 2)], i), data={'data': sentences[randint(0, len(sentences)-1)]})
